### ISSUE TITLE
Window list does not scale to full space with the setting option checked

### ISSUE THREAD

**Issue by xgoku1** [edoz90/numix-cinnamon-transparent#2]
In the setting

Settings > Preferences > Applets > Window list > Configure > Window buttons can have different sizes and use the entire space available

to set the window list to take the entire available area in the panel, does not work.

Solution:
Removing "max-width: 10em;" from ".window-list-item-box" section.

Furthermore, padding changes are were done to accomodate the changes. (optional)
Changes done:
-----------------------------------------------------------------------------------------------------------
.window-list-box {
  spacing: 0px;
  padding-left: 0;
}

to

.window-list-box {
  spacing: 6px;
  padding-left: 10px;
}

-----------------------------------------------------------------------------------------------------------
.window-list-item-box {
  color: #ffffff;
  font-weight: bold;
  padding-left: 0px;
  padding-right: 0px;
  max-width: 10em;

to

.window-list-item-box {
  color: #ffffff;
  font-weight: bold;
  padding-left: 8px;
  padding-right: 8px;
}

**Comment by notdodo** [comment]
This fork is a 

> Transparent version of Numix-Cinnamon Theme with **shorter window list tab**

>  Numix Theme for cinnamon; transparent and **compact** version
