### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by kxli-Ai** [edoz90/numix-cinnamon-transparent#3]
your configuration is cool .
Can you give me the config file and font for powerlevel9k？
Thank you so much

**Comment by notdodo** [comment]
not an issue

**Comment by keepkay** [comment]
抱歉，我不知道如何联系你，我的邮箱：pt.sharkshow@gmail.com
可否给我你的powerlevel9k的配置文件和使用字体？非常感谢

**Comment by kxli-Ai** [comment]
Sorry, I don't know how to contact you. 
My email address: pt.sharkshow@gmail.com
Could you please give me your powerlevel9k configuration files and use fonts? Thank you very much
